### ISSUE TITLE
Organisation access request

### ISSUE THREAD

**Issue by dbrrt** [Novartis/requests#10]
I'd like to be added to Novartis organisation to be able to contribute to existing/new repositories, related to web development (mostly React, Redux, d3 etc...) and Back-end libraries, such as YADA, and Data Science projects.

- **Are you a Novartis employee?** Yes
- 521 : BARRADA3

**Comment by robindo3** [comment]
Hi David, I have sent a request to you to join the Novartis Organization GitHub page.  Enjoy!  -Doug

**Comment by robindo3** [comment]
Completed
