### ISSUE TITLE
join request

### ISSUE THREAD

**Issue by lima1** [Novartis/requests#11]
- **I'm in OncDS and have 2 repositories currently under my own account that I'd like to have listed here (lima1/PureCN and lima1/sttkit) if possible **
- **Do you need access to any specific repos? No**
- **Are you a Novartis employee? Yes**

- **Novartis 521 ID: riestma1**

**Comment by robindo3** [comment]
Hi Markus,  Any additions / modifications must first gain approval through OAK.  There the projects may be formally discussed and approved through our legal council to ensure that it complies with our Novartis data sharing policies.  Please keep me informed as to your request and you may add me as a reviewer to your OAK submission.

**Comment by lima1** [comment]
Hi Doug, thanks for getting back to me so quickly.

My projects have been approved already (OAK id 41652, 28468).  https://github.com/lima1/PureCN is already quite established and I'd like to keep the old URL. Is it possible to add a link here? The other one (https://github.com/lima1/sttkit) I'm happy to move.

**Comment by robindo3** [comment]
Hi Markus, I have invited you to be a member of the Novartis GitHub page, as well as to be a Contributor.  Please accept the invitation that was sent to you.  Right now I have generated the PureCN and sttkit repositories to the Novartis GitHub page as well.  I believe you should have the ability to add and contribute to those repos.  Please let me know.  Cheers, Doug
