### ISSUE TITLE
Request to join

### ISSUE THREAD

**Issue by gusef** [Novartis/requests#12]
- **Why are you joining the Novartis Open Source organization?**
We developed a few R packages that are we currently internally using to do analyses. We are running more and more into the issue that we are trying to publish using figures/data generated using these packages and it would therefore be convenient to be able to point to a publicly available repository.

- **Do you need access to any specific repos?**
No, I would like to add my own.

- **Are you a Novartis employee?** 
yes, I work in the Oncology Data Science group in NIBR 

- **Novartis 521 ID:** gusenda1

**Comment by gusef** [comment]
@robindo3  , sorry to bother again. I just got OAK approval to publish one of our repositories. Could you please give me access. Thank you!
Dan

**Comment by robindo3** [comment]
Hi Daniel,  You have been added to the Novartis GitHub page and as a contributor.  Please check your email and accept the invitation.  Currently, Contributors do not have the access to create their own repositories on the Novartis GitHub page.  Please let me know the name of the repository you would like to create and I will generate it for you.  Cheers, Doug

**Comment by robindo3** [comment]
Please submit another issue to add the repository name to the Novartis GitHub site.
