### ISSUE TITLE
Can I be added to the Novartis GitHub Organisation?

### ISSUE THREAD

**Issue by rjanssens1** [Novartis/requests#13]
- **Why are you joining the Novartis Open Source organization?**
I would like to open source code for a paper. The code is already OAK approved.
- **Do you need access to any specific repos?**
No, I would like to create a new repo.
- **Are you a Novartis employee?**
Yes
- **Novartis 521 ID:**
janssre2

**Comment by robindo3** [comment]
Hi rjanssens1, You have been added to the Novartis GitHub page as an associate and as a contributor.  Please look for the email and accept the invitation.  Cheers, Doug

**Comment by rjanssens1** [comment]
Hi Doug,

Somehow it didn’t work. Could you add me again please?

Best wishes,
Rens
