### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by xanibas** [Novartis/requests#14]
I have joined Novartis GitHub, but I'm unable to push changes to the Novartis/granulator repository:

> git push origin master
(insert github account username)
(insert github password)
remote: Permission to Novartis/granulator.git denied to xanibas.
fatal: unable to access 'https://github.com/Novartis/granulator/': The requested URL returned error: 403

Help is appreciated!

**Comment by dimacus** [comment]
hi @xanibas ,

Sorry for delay, we finally got the admin access to the org and can help you with this.

Can you please fork the granulator repo to your personal account, apply the changes there and create a pull request from your account to Novartis? This way we can merge your changes and it will be audit tracked.

Can you also create an OAK request to make sure that your code changes are reviewed and approved by the appropriate teams? I wan to make sure that neither one of us gets in trouble with legal.

Thank you!

**Comment by kliatsko** [comment]
Closing this one as resolved. Please reach out to me in Teams (kliatni1) if you still have questions!
