### ISSUE TITLE
Request to be added to Novartis GitHub

### ISSUE THREAD

**Issue by angadps** [Novartis/requests#15]
- **Why are you joining the Novartis Open Source organization?**
I need to add repositories to the Novartis GitHub for the work done here at Novartis and be published in manuscripts.
- **Do you need access to any specific repos?**
No
  
- **Are you a Novartis employee?**
Yes

- **Novartis 521 ID:**
singhann

**Comment by robindo3** [comment]
Hi angadps, You have been added to the Novartis GitHub Page, both as an Associate and as a Contributor.  You should have received an email that details the invitation.  Please accept the invitation.  Cheers, Doug
