### ISSUE TITLE
Added to the Novartis organization, but still cannot create a repository

### ISSUE THREAD

**Issue by AnsgarSchuffenhauer** [Novartis/requests#16]
Dear all,
While having been added to the Novartis organization previously (https://github.com/Novartis/requests/issues/9). However I discovered today that I am still not able to create a repository under the Novartis organization. 

The code I wish to publish has been OAK approved for open sourcing as part of the supplementary information to a journal article (https://oak-intra.novartis.com/cgi/users/home?screen=EPrint%3A%3AView&eprintid=43061) . As the article has been accepted now and is at the proof stage, I would like to publish the code now.

**Comment by kliatsko** [comment]
Reached out to Ansgar in Teams
