### ISSUE TITLE
Cannot create a repo

### ISSUE THREAD

**Issue by rjanssens1** [Novartis/requests#17]
Would it be possible to create a repo with the name "UMM-Discovery" for me?
I somehow dont have the rights to create one.

Best,
Rens

**Comment by kliatsko** [comment]
Hi @rjanssens1 please ping me on Teams about this. the process to set up a new repo is pretty straightforward and I can guide you.

**Comment by kliatsko** [comment]
also, please put your full name and Novartis email address in your profile. this will help admins if they need to get in touch with you for something.

**Comment by kliatsko** [comment]
@rjanssens1 please ping me on Teams (kliatni1) and we can work through this. You'll need a legal approval to post code externally but I can walk you through the steps.
