### ISSUE TITLE
Cannot create a repo (I am already added to the organization)

### ISSUE THREAD

**Issue by rjanssens1** [Novartis/requests#18]
- **Why are you joining the Novartis Open Source organization?**
Open source code for paper
- **Do you need access to any specific repos?**
Can someone create the repo "UMM-Discovery" for me and give me access rights?
  
- **Are you a Novartis employee?**
Yes

- **Novartis 521 ID:**
janssre2

**Comment by robindo3** [comment]
Hi rhanssens1, Users do not have the authority to create repos on the official Novartis GitHub pages.  You must go through OAK to gain approval and then I will be able to use this create a repo for you.  -Doug

**Comment by rjanssens1** [comment]
Hi Doug,
Thanks a lot for your reply. I got OAK approval.
See https://oak-intra.novartis.com/cgi/users/home?screen=EPrint%3A%3AView&eprintid=43461.
Could you create a repo for me?
Thanks in advance for your help.
Best Rens

**Comment by robindo3** [comment]
completed
