### ISSUE TITLE
Join Novartis Open Source organisation request

### ISSUE THREAD

**Issue by vudielle** [Novartis/requests#19]
- **Why are you joining the Novartis Open Source organization?** I would like to share a new repository (related to a recent publication, OAK approved)
- **Do you need access to any specific repos?** No, but I would like to open one
  
- **Are you a Novartis employee?** Yes

- **Novartis 521 ID:** delucva3

**Comment by robindo3** [comment]
An invitation has been sent for you to join the Novartis GitHub page.
