### ISSUE TITLE
Request to join NVS repository as member

### ISSUE THREAD

**Issue by andreagrioni** [Novartis/requests#21]
- **Why are you joining the Novartis Open Source organization?**
I am part of the TMDS Mentors Community, which aims to increase the knowledge of data science within Novartis.
We organise monthly sessions with tutorials on general approaches for the analysis of -omics data. For example, a tutorial 
can cover basic commands for reading/writing csv files with R or Python as well as general pipeline for bioinformatics analysis. I was wondering if it could be possible to create a repository under the Novartis GitHub where we can store some of these tutorials.

- **Do you need access to any specific repos?**
No
- **Are you a Novartis employee?**
Yes
- **Novartis 521 ID:**
02116863

Thank you

**Comment by kliatsko** [comment]
sent an invite!

**Comment by kliatsko** [comment]
@andreagrioni 
In order to get permission to post something to the GitHub page, you'll need legal approval through the OAK review.
go/OSI has solid instructions

Please reach out to me on Teams (kliatni1) with any questions. It's hard to keep track of things on this site.
