### ISSUE TITLE
Request to join Novartis GitHub 

### ISSUE THREAD

**Issue by PsiGamma** [Novartis/requests#22]
- **Why are you joining the Novartis Open Source organization?**
I want to release code related to an upcoming publication.
- **Do you need access to any specific repos?**
No, my repo is a standalone.
- **Are you a Novartis employee?**
Yes
- **Novartis 521 ID:**
godinwi1

**Comment by PsiGamma** [comment]
@kliatsko Can you help with this issue?

**Comment by kliatsko** [comment]
Reached out to William via Teams
