### ISSUE TITLE
OAK - Project 46865: AEGIS publication

### ISSUE THREAD

**Issue by CSchleNVS** [Novartis/requests#28]
- **Why are you joining the Novartis Open Source organization?**
We are publishing code to support a publication. (OAK - Project 46865)

- **Do you need access to any specific repos?**
No, we need to create one. 

  
- **Are you a Novartis employee?** 
Yes

- **Novartis 521 ID: schlechb

**Comment by kliatsko** [comment]
Reached out to Christian
