### ISSUE TITLE
Intend to open source a project

### ISSUE THREAD

**Issue by pcallnvs** [Novartis/requests#35]
- **Why are you joining the Novartis Open Source organization?**: We intend to open source a currently internal R package.
- **Do you need access to any specific repos?**: No. I would only need the rights to the eventual repository for the previously mentioned R package.
  
- **Are you a Novartis employee?**: Yes.

- **Novartis 521 ID:**: CALLAPA5

**Comment by kliatsko** [comment]
Invited
