### ISSUE TITLE
Getting Access to Novartis GitHub

### ISSUE THREAD

**Issue by t-nicko4** [Novartis/requests#39]
- **Why are you joining the Novartis Open Source organization?**
 I'd like to have access to open source projects (automation tools for Lab IT).
- **Do you need access to any specific repos?** 
 NO
  
- **Are you a Novartis employee?**
-Yes.

- **Novartis 521 ID:**
 jeanwi1  (wilnick.jean_ext@novartis.com)

**Comment by kliatsko** [comment]
Invited!
