### ISSUE TITLE
need permission to manage Novartis githhb project 'granulator'

### ISSUE THREAD

**Issue by xanibas** [Novartis/requests#4]
- **Why are you joining the Novartis Open Source organization?**
I have contributed to an R package (granulator), currently available on the Github/Novartis account. l need access for submission to Bioconductor and maintenance of the package.
- **Are you a Novartis employee?**
Yes

- **Novartis 521 ID:**
pfistsa4

**Comment by ryaninvents** [comment]
Thanks Sabina... Welcome to the team! 👋
