### ISSUE TITLE
Request to join

### ISSUE THREAD

**Issue by andro-demir** [Novartis/requests#40]
- **Why are you joining the Novartis Open Source organization?** Open source distribution of a code  repository. The content has been successfully accepted for publication at the ICLR 2024 conference, under the OAK ID: 53142. It is important to note that the associated codebase does not incorporate or rely on any data or confidential information from Novartis.

- **Do you need access to any specific repos?** No.
- 
  

- **Are you a Novartis employee?** Yes.
- 

- **Novartis 521 ID:** DEMIRAN1

**Comment by kliatsko** [comment]
I'm joining this story late. Did you get what you need? Ping me on Teams if you need anything.
