### ISSUE TITLE
Co-Pilot program beta-testing

### ISSUE THREAD

**Issue by antonkei** [Novartis/requests#42]
- **Why are you joining the Novartis Open Source organization?**: I want to participate in Github Co-Pilot program and test it as a AI productivity tool for my daily routine with Python and R programming.
- **Do you need access to any specific repos?**: No
  
- **Are you a Novartis employee?**: No, I'm external employee from Epam working in NIBR: CDIP team

- **Novartis 521 ID:** KUKUSAN2

**Comment by kliatsko** [comment]
Reached out in Teams
