### ISSUE TITLE
GitHub Co-Pilot testing

### ISSUE THREAD

**Issue by aupspb** [Novartis/requests#43]
**Why are you joining the Novartis Open Source organization?:** I want to participate in GitHub Co-Pilot program and test it as a tool for my daily work with C#.
**Do you need access to any specific repos?:** No
**Are you a Novartis employee?:** I'm external employee from EPAM. I'm working in NIBR, PLA team.
**Novartis 521 ID:** POGORAN1

**Comment by kliatsko** [comment]
Reached out in Teams
