### ISSUE TITLE
Request to GitHub Co-Pilot

### ISSUE THREAD

**Issue by teplima1** [Novartis/requests#44]
**Why are you joining the Novartis Open Source organization?:** I want to participate in GitHub Co-Pilot program and test it as a tool for my daily work with VS Code and Visual Studio
**Do you need access to any specific repos?:** No
**Are you a Novartis employee?:** I'm external employee from EPAM. I'm working in NIBR, PLA team.
**Novartis 521 ID:** Teplima1

**Comment by kliatsko** [comment]
Reached out in Teams
