### ISSUE TITLE
Request for a new repo within the Novartis github

### ISSUE THREAD

**Issue by orladoylenvs** [Novartis/requests#47]
I'd like to request a new repo to be created with the Novartis github project.

We already have informal approval from legal and we will trigger the OAK process once our private repo is in place. 

Requestor: Orla Doyle
 Desired repo name: validated_packages
 Description: Repository collecting risk assessment data on the packages installed on our Statistical Computing Environment at Novartis. 
 Primary Language: R
 Desired License (preferred is MIT): MIT
 OAK ID(s): 55051
 Users requiring access (5-2-1s and GitHub usernames): 
 doyleor1 - [orladoylenvs]
GIMENIN2 - [ines-gimeno-molina]
CRANENI1 - [thisisnic]
TALBOJA1 - [jtalboys]

**Comment by orladoylenvs** [comment]
@kliatsko fyi this is now fully approved in OAK: https://oak-intra.novartis.com/55051/

**Comment by kliatsko** [comment]
Posted!
https://github.com/Novartis/validated_packages

**Comment by orladoylenvs** [comment]
Thank you so much!
