### ISSUE TITLE
Join request Ansgar Schuffenhauer (schufan1)

### ISSUE THREAD

**Issue by AnsgarSchuffenhauer** [Novartis/requests#9]
- **Why are you joining the Novartis Open Source organization? I wish to create my own repo for code to be open sourced a alongside with a publication (currently in the making)**
- **Do you need access to any specific repos? No**
  
- **Are you a Novartis employee? yes**

- **Novartis 521 ID: schufan1**

**Comment by ryaninvents** [comment]
Thank you! I've invited you to the team. Please reach out via go/osi when you're ready to submit.

**Comment by AnsgarSchuffenhauer** [comment]
@robindo3 Can you please check that I can create a repository
